# Generated by Django 5.0.2 on 2024-07-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterList',
            fields=[
                ('parameterId', models.AutoField(primary_key=True, serialize=False)),
                ('parameterName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('partId', models.AutoField(primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=255)),
                ('partCost', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterVersionHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='myapp.parameterlist')),
                ('parentParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.parameterlist')),
            ],
        ),
        migrations.CreateModel(
            name='PartInputParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partdetails')),
                ('partInputParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parameterlist')),
            ],
        ),
        migrations.CreateModel(
            name='PartOutputParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partdetails')),
                ('partOutputParameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parameterlist')),
            ],
        ),
    ]
