# Generated by Django 4.2.6 on 2023-11-07 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careerpath',
            fields=[
                ('careerpathid', models.CharField(db_column='careerPathID', max_length=4, primary_key=True, serialize=False)),
                ('careerpathname', models.CharField(blank=True, db_column='careerPathName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'careerpath',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParameterHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentParameterID', models.CharField(db_column='parentParameterID', max_length=10)),
                ('childParameterID', models.CharField(db_column='childParameterID', max_length=10)),
                ('noOfDepth', models.IntegerField(db_column='noOfDepth')),
                ('noOfChildren', models.IntegerField(db_column='noOfChildren')),
            ],
            options={
                'db_table': 'parameterhierarchy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parameterlist',
            fields=[
                ('parameterid', models.CharField(db_column='parameterID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='parameterName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'parameterlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ruleinfo',
            fields=[
                ('ruleid', models.IntegerField(primary_key=True, serialize=False)),
                ('support', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('lift', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ruleinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Webservicelist',
            fields=[
                ('webserviceid', models.CharField(db_column='webServiceID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='webServiceName', max_length=100, null=True)),
                ('reputation', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'webservicelist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('transactionid', models.BigIntegerField(db_column='transactionID', primary_key=True, serialize=False)),
                ('stage', models.IntegerField()),
                ('webserviceid', models.ForeignKey(db_column='webServiceID', on_delete=django.db.models.deletion.DO_NOTHING, to='autowscs_app.webservicelist')),
            ],
            options={
                'db_table': 'result',
                'managed': True,
                'unique_together': {('transactionid', 'stage', 'webserviceid')},
            },
        ),
        migrations.CreateModel(
            name='Initialgoalparameter',
            fields=[
                ('transactionid', models.BigIntegerField(db_column='transactionID', primary_key=True, serialize=False)),
                ('iorg', models.CharField(max_length=10)),
                ('parameterid', models.ForeignKey(db_column='parameterID', on_delete=django.db.models.deletion.DO_NOTHING, to='autowscs_app.parameterlist')),
            ],
            options={
                'db_table': 'initialgoalparameter',
                'managed': True,
                'unique_together': {('transactionid', 'iorg', 'parameterid')},
            },
        ),
        migrations.CreateModel(
            name='Outputparameter',
            fields=[
                ('webserviceid', models.ForeignKey(db_column='webServiceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autowscs_app.webservicelist')),
                ('parameterid', models.ForeignKey(db_column='parameterID', on_delete=django.db.models.deletion.DO_NOTHING, to='autowscs_app.parameterlist')),
            ],
            options={
                'db_table': 'outputparameter',
                'managed': True,
                'unique_together': {('webserviceid', 'parameterid')},
            },
        ),
        migrations.CreateModel(
            name='Inputparameter',
            fields=[
                ('webserviceid', models.ForeignKey(db_column='webServiceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autowscs_app.webservicelist')),
                ('parameterid', models.ForeignKey(db_column='parameterID', on_delete=django.db.models.deletion.DO_NOTHING, to='autowscs_app.parameterlist')),
            ],
            options={
                'db_table': 'inputparameter',
                'managed': True,
                'unique_together': {('webserviceid', 'parameterid')},
            },
        ),
    ]
