# Generated by Django 4.2.16 on 2024-11-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parameterlist",
            fields=[
                (
                    "parameterid",
                    models.CharField(
                        db_column="parameterID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="parameterName", max_length=100, null=True
                    ),
                ),
            ],
            options={"db_table": "parameterlist", "managed": True,},
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                ("transactionid", models.BigIntegerField(db_column="transactionID")),
                ("stage", models.IntegerField()),
                ("webserviceid", models.BigIntegerField(db_column="webServiceID")),
            ],
            options={"db_table": "result", "managed": True,},
        ),
        migrations.CreateModel(
            name="Webservicelist",
            fields=[
                (
                    "webserviceid",
                    models.CharField(
                        db_column="webServiceID",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_column="webServiceName",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("reputation", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"db_table": "webservicelist", "managed": True,},
        ),
        migrations.CreateModel(
            name="Outputparameter",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                (
                    "parameterid",
                    models.ForeignKey(
                        db_column="parameterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="servertool.parameterlist",
                    ),
                ),
                (
                    "webserviceid",
                    models.ForeignKey(
                        db_column="webServiceID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="servertool.webservicelist",
                    ),
                ),
            ],
            options={"db_table": "outputparameter", "managed": True,},
        ),
        migrations.CreateModel(
            name="Inputparameter",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                (
                    "parameterid",
                    models.ForeignKey(
                        db_column="parameterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="servertool.parameterlist",
                    ),
                ),
                (
                    "webserviceid",
                    models.ForeignKey(
                        db_column="webServiceID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="servertool.webservicelist",
                    ),
                ),
            ],
            options={"db_table": "inputparameter", "managed": True,},
        ),
        migrations.CreateModel(
            name="Initialgoalparameter",
            fields=[
                ("id", models.AutoField(default=1, primary_key=True, serialize=False)),
                ("transactionid", models.BigIntegerField(db_column="transactionID")),
                ("iorg", models.CharField(max_length=10)),
                (
                    "parameterid",
                    models.ForeignKey(
                        db_column="parameterID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="servertool.parameterlist",
                    ),
                ),
            ],
            options={"db_table": "initialgoalparameter", "managed": True,},
        ),
    ]
