# Generated by Django 4.2.16 on 2024-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servertool", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialgoalparameter",
            name="id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="inputparameter",
            name="id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
